### ISSUE TITLE
[Backend]500 error during login

### ISSUE THREAD

**Issue by yura0611** [ShoppeOrg/shoppe#12]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/68848802/220674017-2d723c85-911c-41e7-96a1-4ea8a3a9f55a.png">

In order to reproduce this issue, enter `yurii@i.ua` as email and press sign in

**Comment by OleksandrPozden** [comment]
[FIXED] with [pull request](https://github.com/ShoppeOrg/shoppe/pull/13)
